name: biocalculator_dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - partd
  - bokeh
  - django==3.1.6
  - pyyaml==5.1
  - torchvision
  - pip
  - pip:
    - opencv-python 
    - django-crispy-forms
    - git+https://github.com/facebookresearch/detectron2.git